### ISSUE TITLE
Default image url

### ISSUE THREAD

**Issue by semeano** [wallin/angular-gravatar#21] opened 2015-02-12 16:24 UTC
I'm setting the options directly on the directive, this way:

    <img class="gravatar" ng-show="app.user.email" gravatar-src="app.user.email" gravatar-size="30" gravatar-default="http%3A%2F%2Fwww.gravatar.com%2Favatar%2F205e460b479e2e5b48aec07710c08d50">

and I'm getting this error:

    GET http://i2.wp.com/http%3A%2F%2Fwww.gravatar.com%2Favatar%2F205e460b479e2e5b48aec07710c08d50 400 (Bad Request)

I don't know where the "http://i2.wp.com/" came from...

**Comment by wallin** [comment] 2015-02-12 17:10
Hey! Looks strange. Could you provide any other configuration options that are using? like default options. The i2 stuff seems to related to [Photon](https://developer.wordpress.com/docs/photon/)

**Comment by semeano** [comment] 2015-02-12 17:15
I'm not setting any options other than those that are on the directive.

**Comment by msmirnov** [comment] 2015-06-04 19:39
I have the same issue. Can you help me?

**Comment by wallin** [comment] 2015-06-04 20:03
Sure. Just post a jsfiddle here that reproduces the problem and I'll have a look

**Comment by msmirnov** [comment] 2015-06-04 20:32
Strangely, jsfiddle working properly. Maybe this is due to the fact that my site is running on localhost. I'll check on the server.

**Comment by wallin** [comment] 2015-06-05 07:24
Interesting. Does the same thing happen if you use the alias `lvh.me` (domain that points to 127.0.0.1, useful when testing subdomains locally)?

**Comment by msmirnov** [comment] 2015-06-08 11:24
Now it works, because I set the default value 'identicon'. The problem occurs only if you specify the wrong links. For example: ```gravatar-default="http://placehold.it/350x150"``` works fine, but ```gravatar-default="http://google.com/"``` returns an error ```GET http://i1.wp.com/https//www.google.com/ 504 (Gateway Timeout)```. Maybe the problem with headers (Content-Type, etc.)?

Thanks.

**Comment by wallin** [comment] 2015-06-10 23:10
Right! So the "problem" is that gravatar most likely redirects to to this URL if the default image URL doesn't return an image.

```bash
$ curl -I http://www.gravatar.com/avatar/46ab5c60ced85b09c35fd31a510206ee\?default\=http://google.com/
HTTP/1.1 302 Found
Accept-Ranges: bytes
Cache-Control: max-age=300
Content-Type: text/html; charset=utf-8
Date: Wed, 10 Jun 2015 23:06:46 GMT
Expires: Wed, 10 Jun 2015 23:11:46 GMT
Last-Modified: Wed, 11 Jan 1984 08:00:00 GMT
Link: <http://www.gravatar.com/avatar/46ab5c60ced85b09c35fd31a510206ee?default=http://google.com/>; rel="canonical"
Location: http://i1.wp.com/google.com/
```

I'm gonna close this issue now, if you don't mind

**Closed** 2015-06-11 07:54 UTC
